### PR TITLE
adding TE-Connectivity_FPC_15P_Pitch1mm_Angled

### PR DESCRIPTION
**Pull request by jeromebeguin**

### CODE REVIEW

**Comment by jkriege2** [comment]
Please fix the two KLC issues and could you provide a datasheet link for this to make review easier?

Thanks,
JAN

**Comment by evanshultz** [comment]
@jeromebeguin Can you please fix the KLC issues and confirm the datasheet? By taking a quick look it appears the footprint is for [1-84952-5 ](http://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=84952&DocType=Customer+Drawing&DocLang=English&DocFormat=pdf&PartCntxt=1-84952-5)or [1-84953-5](http://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=84953&DocType=Customer+Drawing&DocLang=English&DocFormat=pdf&PartCntxt=1-84953-5). I believe the footprints are the same with the difference being the contacts face up or down to support different orientations of cables.

And if you're up for it, writing a Python script to bang out the whole family of connectors (rather than just the 15 pin version) would be great.

**Comment by evanshultz** [comment]
Footprint image:
image

**Comment by poeschlr** [comment]
As with some of your other connectors, please reduce the complexity of the fab layer drawings.

**Comment by evanshultz** [comment]
I'm considering this PR abandoned since the originator closed it.

**Comment by evanshultz** [comment]
I've nearly completed a script for both connector families I mentioned above, including this particular part. Here is an example image:
image

Any feedback is welcome, but I have two specific questions:
1. Should the solder tab pads have a pin number? They're 16 above, but 0 seems to be most common.
1. I drew lines on F.Fab to show the actuator open, similar to how some of the SD card footprints show the position of the card when ejected. Should this be on another layer? Should it be removed?

**Comment by evanshultz** [comment]
@poeschlr @jkriege2 
#1 above is understood since these are just for mounting and not electrical connection. For #2, though, could I get some advice before I generate a PR for this series of connectors? Thanks!

**Comment by SchrodingersGat** [comment]
@evanshultz should the courtyard extend down past the open position of the actuator?

**Comment by evanshultz** [comment]
@SchrodingersGat Thanks for looking.
It certainly can. I will implement that. Should silk go around the actuator's open outline as well?

Anything else? What about the layer for the actuator outline?

**Comment by SchrodingersGat** [comment]
I don't think that the silkscreen should extend down to the open position. I like the way you have drawn the symbol above.

**Comment by evanshultz** [comment]
@SchrodingersGat OK. Thank you. Should the actuator's open position be drawn on F.Fab?

**Comment by SchrodingersGat** [comment]
Yep!

**Pull request closed without merging**
