### PR TITLE
Add TE Connectivity 2041021-4 SD card connector

### PR DESCRIPTION
**Pull request by PTaylor-RA**

### CODE REVIEW

**Comment by poeschlr** [comment]
Sorry for the late review. (I think this pull request go overlooked.)

The problem now is that the [kicad library convention](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) has changed. If you are prepared to rework this footprint to follow this new convention this would be great.
The main new things are:
Component outline on the fab layer (It looks like you used the courtyard layer for that. The courtyard layer represents the space needed for the part itself + a bit more for assembly -> it needs to be 0.25mm outside of the component body or outside of the area described by the pads. Whichever is larger.)

A second reference designator on the fab layer (user text field with text %R)

The silk outline should be visible after part assembly.

3d settings:
The path starts with ${KISYS3DMOD}/
scale = (1,1,1)
rotation = (0,0,0)
offset = (0,0,0)

The documentation field includes a link to a datasheet
Fill out the keyword field

What does this rectangle on the eco layer represent?

**Comment by evanshultz** [comment]
@PTaylor-RA Can you please provide a datasheet and address the violations mentioned above for this part? It would be great to add your contribution to the KiCad library.

**Comment by poeschlr** [comment]
@PTaylor-RA am i right in assuming that you lost interest in this pull request?

**Comment by chmorgan** [comment]
Hi all. I can take a look at cleaning this part up. Would it help to get my part into the PR review process?

**Comment by PTaylor-RA** [comment]
Rene,
My apologies. I am currently under tight time constraints and don't have
time right now to make revisions.





* Peter Taylor* | Electronics Engineer
 *P:* 719.330.2052
 Ray Allen Manufacturing | J&J Dog Supplies
 975 Ford Street, Colorado Springs, CO 80915
------------------------------
www.rayallen.com | www.jjdog.com | ptaylor@rayallen.com <email@rayallen.com>

**Comment by chmorgan** [comment]
I'll take a look at this in the near future. I am trying to bargain my way to getting my PRs reviewed and approved and if this helps it's not difficult to match the klc.

**Comment by poeschlr** [comment]
@PTaylor-RA or @chmorgan if any one of you is interested in getting this footprint merged, please do so in the new repo https://github.com/KiCad/kicad-footprints. This repo is declared legacy and therefore archived in preparation for the v5 release.

**Pull request closed without merging**
